version: '3.8'

services:
  terraform:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - ./direnv/config.toml:/root/.config/direnv/config.toml

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
